### ISSUE TITLE
Bug report: Navigate to a URL is not working

### ISSUE THREAD

**Issue by doggy8088** [jaktestowac/vscode-playwright-snippets-ui#1]
Please check my video clip:

<video src="https://github.com/user-attachments/assets/01818a95-d22c-4d6b-ad9c-2c92043b7a6a"></video>

I checked all items, only the first one `Navigate to a URL` is not working.

**Comment by Freudenberger** [comment]
Thank You for reporting!

Fixed!
It was an issue in https://github.com/jaktestowac/vscode-playwright-snippets
and it was fixed in: https://marketplace.visualstudio.com/items?itemName=jaktestowac-pl.vsc-playwright-snippets v0.0.20
